-- 코드를 입력하세요
# SELECT FLAVOR
# FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDERS
# FROM (
#     SELECT FLAVOR, TOTAL_ORDER FROM JULY
#     UNION ALL
#     SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
# ) AS combined_table
# GROUP BY FLAVOR
# ORDER BY TOTAL_ORDERS DESC) AS TOP_F
# LIMIT 3

SELECT H.FLAVOR
FROM FIRST_HALF H INNER JOIN (
    SELECT FLAVOR, sum(TOTAL_ORDER) as 'TO'
    FROM JULY
    GROUP BY FLAVOR) J
    ON H.FLAVOR = J.FLAVOR
ORDER BY (H.TOTAL_ORDER+ J.TO) DESC
LIMIT 3

