-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE 1=1 AND S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) > 0
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY D.ID